apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production-raspberrypi
bases:
  - ../../base
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
images:
  - name: backend-raspberrypi-data01
    newName: alpine
    newTag: "3.12"
