apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: os
    app.kubernetes.io/name: raspberrypi-data
  annotations:
    command: &cmd 'log() { local level=$1; local message=$2; local timestamp=$(date +"%Y/%m/%d %H:%M:%S"); echo "[$level] $timestamp $message"; }; info() { local message=$1; log "INFO" "$message"; }; error() { local message=$1; log "ERROR" "$message"; }; while true; do temperature=$(vcgencmd measure_temp); if [ $? -eq 0 ]; then info "$(hostname) Temperature: $temperature"; else error "$(hostname) Failed to retrieve temperature"; fi; sleep 60; done'
  name: backend-raspberrypi-data01
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: raspberrypi-data
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raspberrypi-data
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: backend-raspberrypi-data01
          image: backend-raspberrypi-data01
          securityContext:
            privileged: true
          command:
            - nsenter
            - --mount=/proc/1/ns/mnt
            - --
            - bash
            - -c
            - *cmd
